services:
  app:
    build: .  # Usa il Dockerfile per creare l'immagine
    container_name: waste_app
    env_file:
      - .env
    volumes:
      - ./:/app
    working_dir: /app
    command: python main.py
    depends_on:
      - db
    ports:
      - "80:80"

  db:
    image: postgres:16
    container_name: waste_db
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

volumes:
  postgres_data:
